version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: api:dev
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash
